- hosts: all
become: yes
tasks:
- name: instalar Docker
apt:
name: docker.io
state: present
update_cache: true

-name: instalar Docker-compose
apt:
name: docker-compose
state: present
update_cache: true